# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: daily

  # Docker - cryfs
  - package-ecosystem: "docker"
    directory: "/cryfs"
    schedule:
      interval: "weekly"

  # Docker - encfs
  - package-ecosystem: "docker"
    directory: "/encfs"
    schedule:
      interval: "weekly"

  # Python (Poetry/pyproject.toml & poetry.lock supported via 'pip' ecosystem)
  - package-ecosystem: "pip"
    directory: "/" # adjust if your pyproject lives elsewhere
    schedule:
      interval: "daily"
      day: "sunday"
      time: "04:10"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:20"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"